server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/files;

    location / {        
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;

        add_before_body /theme/header.html;
        add_after_body  /theme/footer.html;
    }

    location /theme/ {
        root /etc/nginx;
        expires 7d;
        add_header Cache-Control "public";
    }
}